services:
  database:
    image: devikadockhub/pyapp:database-image
    deploy:
      replicas: 2
    ports:
      - "3306:3306"
    networks:
      - python-network


  auth:
    image: devikadockhub/pyapp:auth-image
    deploy:
      replicas: 2
    ports:
      - "5001:5001"
    networks:
      - python-network
    depends_on:
      - database

  borrow:
    image: devikadockhub/pyapp:borrow-image
    deploy:
      replicas: 2
    ports:
      - "5003:5003"
    networks:
      - python-network
    depends_on:
      - database

  book:
    image: devikadockhub/pyapp:book-image
    deploy:
      replicas: 2
    ports:
      - "5002:5002"
    networks:
      - python-network
    depends_on:
      - database

  frontend:
    image: devikadockhub/pyapp:frontend-image
    deploy:
      replicas: 2
    ports:
      - "5000:5000"
    networks:
      - python-network
    depends_on:
      - auth
      - borrow
      - book


networks:
  python-network:
    driver: overlay

